# Generated by Django 4.1.1 on 2022-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaBrokerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bootstrap_server', models.CharField(default='Kafka Topic Data', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker Data',
                'verbose_name_plural': 'Broker Access',
                'db_table': 'tbl_broker',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KafkaConsumerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(default='Kafka Topic Data', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consumer Data',
                'verbose_name_plural': 'Consumer Access',
                'db_table': 'tbl_consumer',
                'ordering': ('-created_at',),
            },
        ),
    ]
