# Generated by Django 4.1.1 on 2022-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaCosumerLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bootstrap_server', models.CharField(default='Kafka Bootstrap Server Data', max_length=1000)),
                ('topic', models.CharField(default='Kafka Topic Data', max_length=1000)),
                ('partition', models.CharField(default='Kafka Partition Data', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consumer Data',
                'verbose_name_plural': 'Consumer Logs',
                'db_table': 'tbl_consumer_log',
                'ordering': ('-created_at',),
            },
        ),
    ]
