# Generated by Django 4.1.1 on 2022-09-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0002_kafkacosumerlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplunkCosumerSubscribeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bootstrap_servers', models.CharField(default='Kafka Bootstrap Server Data', max_length=1000)),
                ('topic', models.CharField(default='Kafka Topic Data', max_length=1000)),
                ('partition', models.CharField(default='Kafka Partition Data', max_length=1000)),
                ('subscribe', models.BooleanField(default=True)),
                ('http_event_collector_key', models.CharField(default='http_event_collector_key', max_length=1000)),
                ('http_event_collector_host', models.CharField(default='http_event_collector_host', max_length=1000)),
                ('index', models.CharField(default='Splunk index', max_length=1000)),
                ('sourcetype', models.CharField(default='Sourcetype Splunk', max_length=1000)),
                ('source', models.CharField(default='Source Splunk', max_length=1000)),
                ('host', models.CharField(default='Splunk Host', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Splunk Data',
                'verbose_name_plural': 'Splunk Logs',
                'db_table': 'tbl_splunk_subscribe',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='KafkaCosumerLogs',
        ),
    ]
