# Generated by Django 4.0.3 on 2022-09-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0003_kafkaproducermodel_splunkcosumersubscribemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaAdminClientModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bootstrap_servers', models.CharField(default='Kafka Admin Server Data', max_length=1000)),
                ('topics', models.CharField(default='Kafka Admin Data', max_length=1000)),
                ('partition', models.IntegerField(default='Kafka Admin Data', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Application Data',
                'verbose_name_plural': 'Admin Logs',
                'db_table': 'tbl_admin_client',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='kafkaproducermodel',
            name='partition',
            field=models.IntegerField(default='Kafka Partition Data', max_length=1000),
        ),
    ]
