# Generated by Django 4.1.1 on 2022-09-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0003_splunkcosumersubscribemodel_delete_kafkacosumerlogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kafkabrokermodel',
            old_name='bootstrap_server',
            new_name='bootstrap_servers',
        ),
    ]
