# Generated by Django 4.0.3 on 2022-09-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0004_kafkaadminclientmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafkaadminclientmodel',
            name='partition',
            field=models.IntegerField(default='Kafka Admin Data'),
        ),
        migrations.AlterField(
            model_name='kafkaproducermodel',
            name='partition',
            field=models.IntegerField(default='Kafka Partition Data'),
        ),
    ]
